### ISSUE TITLE
V1.0 produces TypeError 

### ISSUE THREAD

**Issue by leofonic** [ivoba-oxid/oxid-sitemap#2]
When installed as described in the readme, composer installs V1.0, and this produces an exception in Oxid logfile:
message Argument 1 passed to Ivoba\OxidSiteMap\Query\AbstractQuery::__construct() must be an instance of oxLegacyDb, instance of OxidEsales\Eshop\Core\Database\Adapter\Doctrine\Database given

**Comment by ivoba** [comment]
Yes i did not make a release for  2.0.0 and 1.0.0 is for OXID 5.
2.0.0 is released now.

So installation should work now and correctly pick v2 when using OXID6 on `composer require ivoba-oxid/oxid-sitemap`
