### ISSUE TITLE
composer.json contains invalid oxid version

### ISSUE THREAD

**Issue by alexschwarz89** [ivoba-oxid/oxid-sitemap#6]
```
  "require": {
    "php": ">=7.1",
    "oxid-esales/oxideshop-ce": "^v6.5.4"
  },
```

Oxid 6.5.4 does not exist afaik.

**Comment by ivoba** [comment]
@alexschwarz89 it does:
https://github.com/OXID-eSales/oxideshop_ce/releases/tag/v6.5.4

I guess you meant the whole OXID 6.2 shop, which is actually just an alias to the meta_package:
https://github.com/OXID-eSales/oxideshop_metapackage_ce/releases

:)
